version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.19.1-browsers  # Includes Chrome pre-installed

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  test:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
      - run:
          name: Install Chrome
          command: |
            sudo apt update
            sudo apt install -y wget curl
            wget -qO - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt update
            sudo apt install -y google-chrome-stable
      - run:
          name: Set CHROME_BIN
          command: echo 'export CHROME_BIN=/usr/bin/google-chrome' >> $BASH_ENV
      - run:
          name: Run Unit Tests with Code Coverage
          command: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
      - run:
          name: Check Coverage Threshold
          command: |
            COVERAGE=$(grep -Po '"lines": \{"total":\d+,.*?"covered":\d+.*?"pct":\K\d+' coverage/coverage-summary.json)
            echo "Code coverage is $COVERAGE%"
            if [ "$COVERAGE" -lt 80 ]; then
              echo "Code coverage is below 80%. Failing the pipeline."
              exit 1
            fi
      - persist_to_workspace:
          root: .
          paths:
            - coverage
            - sonar-project.properties

  sonar-analysis:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Fix LCOV Paths for SonarCloud
          command: |
            if [ -f coverage/lcov.info ]; then
              echo "Fixing LCOV paths..."
              sed -i 's|SF:.*/src|SF:src|' coverage/lcov.info
              head -n 10 coverage/lcov.info
            else
              echo "lcov.info not found"
              exit 1
            fi
      - run:
          name: Run SonarCloud Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=pankaj-vaidya_Hello-World_CircleCI \
              -Dsonar.organization=pankaj-vaidya \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.token=$SONAR_TOKEN \
              -Dsonar.sources=src \
              -Dsonar.inclusions=src/**/*.ts \
              -Dsonar.exclusions=**/*.spec.ts \
              -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
              -Dsonar.qualitygate.wait=true

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - install
      - test:
          requires:
            - install
      - sonar-analysis:
          requires:
            - test 
