version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17  # Use Node.js 18.17 (or your required version)

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  lint:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
      - run:
          name: Run Linter
          command: npm run lint

  test:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
      - run:
          name: Run Tests
          command: npm test

  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
      - run:
          name: Build Angular App
          command: npm run build -- --configuration=production
      - persist_to_workspace:
          root: dist
          paths:
            - "**"

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: Deploy Application
          command: |
            echo "Deploying the application..."
            # Add your deployment commands here (e.g., Firebase, AWS, Netlify)

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - lint
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: development
