version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  test-and-analyze:
    docker:
      - image: cimg/node:18.20  # Updated Node.js version
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Run Tests
          command: npm run test -- --watch=false --code-coverage
      - run:
          name: Install SonarScanner
          command: npm install -g sonar-scanner
      - run:
          name: Run SonarCloud Analysis
          command: sonar-scanner -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  test-and-analyze:
    jobs:
      - test-and-analyze
