version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

executors:
  node-executor:
    docker:
      - image: cimg/node:18.19.1

jobs:
  build-and-scan:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Build Angular App
          command: npm run build -- --configuration=production
      - run:
          name: Run Tests with Coverage
          command: npm test -- --watch=false --code-coverage
      - sonarcloud/scan

workflows:
  version: 2
  build-analyze:
    jobs:
      - build-and-scan
